// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateAdminUser(ctx context.Context, db DBTX, arg CreateAdminUserParams) (CreateAdminUserRow, error)
	CreateUser(ctx context.Context, db DBTX, arg CreateUserParams) (CreateUserRow, error)
	GetUserByEmail(ctx context.Context, db DBTX, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
