// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

type Product struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Price     interface{} `json:"price"`
	Stock     int64       `json:"stock"`
	Isdeleted bool        `json:"isdeleted"`
}
