// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, db DBTX, arg CreateProductParams) (Product, error)
	DeleteProductByID(ctx context.Context, db DBTX, id int64) error
	GetFilteredProducts(ctx context.Context, db DBTX, arg GetFilteredProductsParams) ([]Product, error)
	GetProductByID(ctx context.Context, db DBTX, id int64) (Product, error)
	GetProductByIDForAdmin(ctx context.Context, db DBTX, id int64) (Product, error)
	// go-type: min=float64
	// go-type: max=float64
	GetProducts(ctx context.Context, db DBTX) ([]Product, error)
	GetProductsForAdmin(ctx context.Context, db DBTX, arg GetProductsForAdminParams) ([]Product, error)
	UpdateProductByID(ctx context.Context, db DBTX, arg UpdateProductByIDParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
