// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, db DBTX, arg CreateProductParams) (Product, error)
	DeleteProductByID(ctx context.Context, db DBTX, id int64) (Product, error)
	GetAllProducts(ctx context.Context, db DBTX) ([]Product, error)
	GetAllProductsForAdmin(ctx context.Context, db DBTX) ([]Product, error)
	GetFilterdProducts(ctx context.Context, db DBTX, arg GetFilterdProductsParams) ([]Product, error)
	GetProductByID(ctx context.Context, db DBTX, id int64) (Product, error)
	UpdateProductByID(ctx context.Context, db DBTX, arg UpdateProductByIDParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
